### ISSUE TITLE
The problem of model.py

### ISSUE THREAD

**Issue by Erwin2233** [miccaiif/DGMIL#9]
I didn't find the model of mae,and the function of mae is a projection,the same as projection768

**Comment by Erwin2233** [comment]
@miccaiif

**Comment by miccaiif** [comment]
> @miccaiif

Thank you for your attention! We pre-trained a feature extractor using the official MAE code and extracted features based on it. The official code of MAE can be referred to at the link https://github.com/facebookresearch/mae. During our training process, we only use a projector for feature mapping, while the features pre-extracted by MAE remain unchanged. This also means that the MAE model is fixed in our experiments.
